### ISSUE TITLE
Modulenotfounderror

### ISSUE THREAD

**Issue by DavidMcSalley97** [Deadpool2000/Paybag#3]
➜  Paybag git:(master) python paybag.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Paybag/paybag.py", line 10, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

**Comment by Deadpool2000** [comment]
Try upgrading packages 

$ apt upgrade

Then run -

$ pip3 install prettytable

**Comment by alitheDev** [comment]
install preetytable via pip

**Comment by DavidMcSalley97** [comment]
worked thanks
